export const STATS = [
  {
    id: 'customers',
    label: 'Total Customers',
    value: '1,248',
    unit: '',
    change: '+12.5% from last month',
    tone: 'up' as const,
    icon: 'customers',
    mobileSpan: 'full' as const,
  },
  {
    id: 'credit',
    label: 'Total Credit',
    value: '85,420.00',
    unit: 'PKR',
    change: '+8.4% from last month',
    tone: 'up' as const,
    icon: 'credit',
    mobileSpan: 'half' as const,
  },
  {
    id: 'debit',
    label: 'Total Debit',
    value: '42,180.00',
    unit: 'PKR',
    change: '+6.2% from yesterday',
    tone: 'down' as const,
    icon: 'debit',
    mobileSpan: 'half' as const,
  },
  {
    id: 'tx',
    label: "Today's Transactions",
    value: '24',
    unit: '',
    change: '+5.3% from yesterday',
    tone: 'up' as const,
    icon: 'tx',
    mobileSpan: 'full' as const,
  },
]

export const BAR_DAYS = [
  { label: 'May 11', credit: 62, debit: 38 },
  { label: 'May 12', credit: 78, debit: 45 },
  { label: 'May 13', credit: 55, debit: 70 },
  { label: 'May 14', credit: 88, debit: 42 },
  { label: 'May 15', credit: 70, debit: 58 },
  { label: 'May 16', credit: 95, debit: 48 },
  { label: 'May 17', credit: 82, debit: 65 },
]

export const TREND = [42, 48, 45, 58, 62, 70, 78]

export const TRANSACTIONS = [
  {
    id: 'TX-1042',
    customer: 'ABC Petroleum',
    type: 'Debit' as const,
    product: 'Diesel',
    amount: '50,000.00',
    balance: '328,400.00',
    when: '17 May 2026 · 10:24 AM',
    by: 'Admin',
  },
  {
    id: 'TX-1041',
    customer: 'XYZ Fuel Station',
    type: 'Credit' as const,
    product: 'Payment',
    amount: '20,000.00',
    balance: '348,400.00',
    when: '17 May 2026 · 09:12 AM',
    by: 'Admin',
  },
  {
    id: 'TX-1040',
    customer: 'City Transport Co.',
    type: 'Credit' as const,
    product: 'CNG · Monthly',
    amount: '95,200.00',
    balance: '404,900.00',
    when: '16 May 2026 · 04:45 PM',
    by: 'Admin',
  },
  {
    id: 'TX-1039',
    customer: 'Green Valley Depot',
    type: 'Debit' as const,
    product: 'Lubricants',
    amount: '22,800.00',
    balance: '309,700.00',
    when: '16 May 2026 · 01:18 PM',
    by: 'Admin',
  },
  {
    id: 'TX-1038',
    customer: 'Highway Filling',
    type: 'Credit' as const,
    product: 'Petrol · 1,500 L',
    amount: '135,000.00',
    balance: '332,500.00',
    when: '15 May 2026 · 11:02 AM',
    by: 'Admin',
  },
]
